### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by shmu26** [dethlex/headset-switcher#1]
Kubuntu 20.04
I ran
`go get -u github.com/dethlex/headset-switcher`
and at the end I got:
`# pkg-config --cflags  -- gtk+-3.0 appindicator3-0.1
pkg-config: exec: "pkg-config": executable file not found in $PATH`

My Go info:
`go version 
go version go1.16.5 linux/amd64`

`go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/shmuel/.cache/go-build"
GOENV="/home/shmuel/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/shmuel/Projects/Proj1/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/shmuel/Projects/Proj1"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.5"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build73582358=/tmp/go-build -gno-record-gcc-switches"`

**Comment by dethlex** [comment]
Hello!
Have you installed pkg-config?
```
sudo apt-get update
sudo apt-get install pkg-config
```

Possibly, you might need to install these packages too:
`sudo apt-get install libgtk-3-dev libappindicator3-dev`

**Comment by shmu26** [comment]
Thanks.
I installed all suggested packages. Now I am getting:
go get -u github.com/dethlex/headset-switcher
package embed: unrecognized import path "embed"
(import path does not begin with hostname)

**Comment by dethlex** [comment]
I guess your GOPATH isn't correct.
Try to reinstall golang and set the right environment variables:
```
sudo apt-get purge golang*
wget https://golang.org/dl/go1.16.5.linux-amd64.tar.gz
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz
mkdir -p ~/go
echo "export GOPATH=$HOME/go" >> ~/.bashrc
echo "export PATH=$PATH:$HOME/go/bin:/usr/local/go/bin" >> ~/.bashrc
source ~/.bashrc
```

**Comment by shmu26** [comment]
Thanks. I think part of the problem is I am using Fish rather than Bash as
my shell, and I was following instructions for Bash. My bad.

**Comment by dethlex** [comment]
Ok, no problem! If something helped you, I will close the issue.
